# Extracción de Datos de la API del Banco Mundial

In [1]:
# importar librerías
import wbgapi as wb
import pandas as pd

In [4]:
# crear listas de países e indicadores
country_list = [
                "AFG", "ARE", "ARG", "AUS", "AUT", "BFA", "BRA", "CAN", "CHE", "CHN",
                "COL", "CRI", "CUB", "DEU", "DNK", "DZA", "ECU", "EGY", "ESP", "FIN", 
                "FJI", "GBR", "GRC", "IND", "JPN", "KEN", "KHM", "MAR", "MEX", "NER", 
                "NLD", "NOR", "NPL", "NZL", "RUS", "RWA", "SAU", "SGP", "SLE", "TCD", 
                "USA", "VEN", "WSM", "ZAF"                
               ]

indicators_list = [
                 "SP.DYN.LE00.IN", "SP.DYN.LE00.FE.IN", "SP.DYN.LE00.MA.IN", "SP.POP.GROW",
                 "SP.RUR.TOTL.ZG", "SP.URB.GROW", "SP.POP.TOTL", "SP.URB.TOTL", "SP.RUR.TOTL"
                 "SP.POP.TOTL.MA.IN", "SP.POP.TOTL.FE.IN", "SP.POP.0014.TO", "SP.POP.0014.MA.IN"
                 "SP.POP.0014.FE.IN", "SP.POP.1564.TO", "SP.POP.1564.MA.IN", "SP.POP.1564.FE.IN",
                 "SP.POP.65UP.TO", "SP.POP.65UP.MA.IN", "SP.POP.65UP.FE.IN", "NY.GDP.PCAP.KD.ZG"
                 "NY.GDP.PCAP.CD", "NY.GDP.DEFL.KD.ZG", "FP.CPI.TOTL.ZG", "SE.SEC.CUAT.LO.ZS",
                 "SE.SEC.CUAT.UP.ZS", "SE.SEC.CUAT.PO.ZS", "SE.SEC.CMPT.LO.ZS", "SH.XPD.GHED.PC.CD"
                 "SH.XPD.OOPC.PC.CD", "SH.XPD.PVTD.PC.CD"
                  ]

In [5]:
# Obtener los datos de la API del Banco Mundial
df_api = wb.data.DataFrame(indicators_list, country_list, mrv=36).reset_index()

In [6]:
df_api

,economy,series,YR1987,YR1988,YR1989,YR1990,YR1991,YR1992,YR1993,YR1994,...,YR2013,YR2014,YR2015,YR2016,YR2017,YR2018,YR2019,YR2020,YR2021,YR2022
0,AFG,FP.CPI.TOTL.ZG,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,7.385772e+00,4.673996e+00,-6.617092e-01,4.383892e+00,4.975952e+00,6.261491e-01,2.302373e+00,NaN,NaN,NaN
1,AFG,NY.GDP.DEFL.KD.ZG,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,4.822785e+00,5.669445e-01,2.447563e+00,-2.197526e+00,2.403656e+00,2.071349e+00,6.521480e+00,7.821667e+00,4.774289e-01,NaN
2,AFG,SE.SEC.CMPT.LO.ZS,NaN,NaN,NaN,NaN,NaN,NaN,2.168611e+01,NaN,...,NaN,NaN,NaN,5.252132e+01,5.469328e+01,5.673693e+01,5.972179e+01,NaN,NaN,NaN
3,AFG,SE.SEC.CUAT.LO.ZS,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,1.312581e+01,NaN,NaN,NaN,NaN,NaN,1.163192e+01,1.534292e+01
4,AFG,SE.SEC.CUAT.PO.ZS,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,4.704880e+00,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1007,ZAF,SP.POP.TOTL,3.611933e+07,3.739385e+07,3.866868e+07,3.987757e+07,4.091096e+07,4.176076e+07,4.252544e+07,4.326798e+07,...,5.387362e+07,5.472955e+07,5.587650e+07,5.642227e+07,5.664121e+07,5.733964e+07,5.808706e+07,5.880193e+07,5.939226e+07,5.989388e+07
1008,ZAF,SP.POP.TOTL.FE.IN,1.860422e+07,1.923134e+07,1.985855e+07,2.045496e+07,2.097209e+07,2.147196e+07,2.200607e+07,2.252280e+07,...,2.783750e+07,2.822886e+07,2.872109e+07,2.900411e+07,2.917594e+07,2.951729e+07,2.987911e+07,3.022114e+07,3.049765e+07,3.072588e+07
1009,ZAF,SP.RUR.TOTL.ZG,2.425981e+00,2.386537e+00,2.259287e+00,1.975314e+00,1.474632e+00,1.030558e+00,7.807271e-01,6.864282e-01,...,-6.707473e-02,1.324969e-01,6.175991e-01,-4.972837e-01,-1.092206e+00,-2.642846e-01,-2.051978e-01,-2.907605e-01,-5.227356e-01,-6.883203e-01
1010,ZAF,SP.URB.GROW,4.562023e+00,4.518988e+00,4.392617e+00,4.106003e+00,3.547016e+00,2.972648e+00,2.721095e+00,2.629444e+00,...,2.181680e+00,2.386572e+00,2.873153e+00,1.760214e+00,1.163250e+00,1.989500e+00,2.047266e+00,1.965305e+00,1.728207e+00,1.557749e+00
1011,ZAF,SP.URB.TOTL,1.821823e+07,1.906040e+07,1.991631e+07,2.075109e+07,2.150034e+07,2.214907e+07,2.276004e+07,2.336644e+07,...,3.436760e+07,3.519767e+07,3.622362e+07,3.686688e+07,3.729824e+07,3.804772e+07,3.883468e+07,3.960545e+07,4.029586e+07,4.092849e+07

In [45]:
# obtener los nombres de los países e indicadores
countries_info = wb.economy.info().table()
indicators_info = wb.series.info().table()

In [49]:
# Mapear los nombres de los países y los nombres de los indicadores en el DataFrame
df_api['country_name'] = df_api['economy'].map(lambda x: next((country[1] for country in countries_info if country[0] == x), ''))
df_api['indicator_name'] = df_api['series'].map(lambda x: next((indicator[1] for indicator in indicators_info if indicator[0] == x), ''))

In [50]:
# Verificar los resultados
df_api

,economy,series,YR1987,YR1988,YR1989,YR1990,YR1991,YR1992,YR1993,YR1994,...,YR2015,YR2016,YR2017,YR2018,YR2019,YR2020,YR2021,YR2022,country_name,indicator_name
0,AFG,FP.CPI.TOTL.ZG,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,-6.617092e-01,4.383892e+00,4.975952e+00,6.261491e-01,2.302373e+00,NaN,NaN,NaN,Afghanistan,"Inflation, consumer prices (annual %)"
1,AFG,NY.GDP.DEFL.KD.ZG,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,2.447563e+00,-2.197526e+00,2.403656e+00,2.071349e+00,6.521480e+00,7.821667e+00,4.774289e-01,NaN,Afghanistan,"Inflation, GDP deflator (annual %)"
2,AFG,SE.SEC.CMPT.LO.ZS,NaN,NaN,NaN,NaN,NaN,NaN,2.168611e+01,NaN,...,NaN,5.252132e+01,5.469328e+01,5.673693e+01,5.972179e+01,NaN,NaN,NaN,Afghanistan,"Lower secondary completion rate, total (% of r..."
3,AFG,SE.SEC.CUAT.LO.ZS,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,1.312581e+01,NaN,NaN,NaN,NaN,NaN,1.163192e+01,1.534292e+01,Afghanistan,"Educational attainment, at least completed low..."
4,AFG,SE.SEC.CUAT.PO.ZS,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,4.704880e+00,NaN,Afghanistan,"Educational attainment, at least completed pos..."
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1007,ZAF,SP.POP.TOTL,3.611933e+07,3.739385e+07,3.866868e+07,3.987757e+07,4.091096e+07,4.176076e+07,4.252544e+07,4.326798e+07,...,5.587650e+07,5.642227e+07,5.664121e+07,5.733964e+07,5.808706e+07,5.880193e+07,5.939226e+07,5.989388e+07,South Africa,"Population, total"
1008,ZAF,SP.POP.TOTL.FE.IN,1.860422e+07,1.923134e+07,1.985855e+07,2.045496e+07,2.097209e+07,2.147196e+07,2.200607e+07,2.252280e+07,...,2.872109e+07,2.900411e+07,2.917594e+07,2.951729e+07,2.987911e+07,3.022114e+07,3.049765e+07,3.072588e+07,South Africa,"Population, female"
1009,ZAF,SP.RUR.TOTL.ZG,2.425981e+00,2.386537e+00,2.259287e+00,1.975314e+00,1.474632e+00,1.030558e+00,7.807271e-01,6.864282e-01,...,6.175991e-01,-4.972837e-01,-1.092206e+00,-2.642846e-01,-2.051978e-01,-2.907605e-01,-5.227356e-01,-6.883203e-01,South Africa,Rural population growth (annual %)
1010,ZAF,SP.URB.GROW,4.562023e+00,4.518988e+00,4.392617e+00,4.106003e+00,3.547016e+00,2.972648e+00,2.721095e+00,2.629444e+00,...,2.873153e+00,1.760214e+00,1.163250e+00,1.989500e+00,2.047266e+00,1.965305e+00,1.728207e+00,1.557749e+00,South Africa,Urban population growth (annual %)
1011,ZAF,SP.URB.TOTL,1.821823e+07,1.906040e+07,1.991631e+07,2.075109e+07,2.150034e+07,2.214907e+07,2.276004e+07,2.336644e+07,...,3.622362e+07,3.686688e+07,3.729824e+07,3.804772e+07,3.883468e+07,3.960545e+07,4.029586e+07,4.092849e+07,South Africa,Urban population

In [51]:
df_api.columns

Index(['economy', 'series', 'YR1987', 'YR1988', 'YR1989', 'YR1990', 'YR1991',
       'YR1992', 'YR1993', 'YR1994', 'YR1995', 'YR1996', 'YR1997', 'YR1998',
       'YR1999', 'YR2000', 'YR2001', 'YR2002', 'YR2003', 'YR2004', 'YR2005',
       'YR2006', 'YR2007', 'YR2008', 'YR2009', 'YR2010', 'YR2011', 'YR2012',
       'YR2013', 'YR2014', 'YR2015', 'YR2016', 'YR2017', 'YR2018', 'YR2019',
       'YR2020', 'YR2021', 'YR2022', 'country_name', 'indicator_name'],
      dtype='object')

In [52]:
# Reordenar las columnas en el DataFrame
df_api = df_api[['country_name', 'economy', 'indicator_name', 'series', 
                 'YR1987', 'YR1988', 'YR1989', 'YR1990', 'YR1991',
                 'YR1992', 'YR1993', 'YR1994', 'YR1995', 'YR1996', 'YR1997', 'YR1998',
                 'YR1999', 'YR2000', 'YR2001', 'YR2002', 'YR2003', 'YR2004', 'YR2005',
                 'YR2006', 'YR2007', 'YR2008', 'YR2009', 'YR2010', 'YR2011', 'YR2012',
                 'YR2013', 'YR2014', 'YR2015', 'YR2016', 'YR2017', 'YR2018', 'YR2019',
                 'YR2020', 'YR2021', 'YR2022'
                ]]

In [53]:
df_api

,country_name,economy,indicator_name,series,YR1987,YR1988,YR1989,YR1990,YR1991,YR1992,...,YR2013,YR2014,YR2015,YR2016,YR2017,YR2018,YR2019,YR2020,YR2021,YR2022
0,Afghanistan,AFG,"Inflation, consumer prices (annual %)",FP.CPI.TOTL.ZG,NaN,NaN,NaN,NaN,NaN,NaN,...,7.385772e+00,4.673996e+00,-6.617092e-01,4.383892e+00,4.975952e+00,6.261491e-01,2.302373e+00,NaN,NaN,NaN
1,Afghanistan,AFG,"Inflation, GDP deflator (annual %)",NY.GDP.DEFL.KD.ZG,NaN,NaN,NaN,NaN,NaN,NaN,...,4.822785e+00,5.669445e-01,2.447563e+00,-2.197526e+00,2.403656e+00,2.071349e+00,6.521480e+00,7.821667e+00,4.774289e-01,NaN
2,Afghanistan,AFG,"Lower secondary completion rate, total (% of r...",SE.SEC.CMPT.LO.ZS,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,5.252132e+01,5.469328e+01,5.673693e+01,5.972179e+01,NaN,NaN,NaN
3,Afghanistan,AFG,"Educational attainment, at least completed low...",SE.SEC.CUAT.LO.ZS,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,1.312581e+01,NaN,NaN,NaN,NaN,NaN,1.163192e+01,1.534292e+01
4,Afghanistan,AFG,"Educational attainment, at least completed pos...",SE.SEC.CUAT.PO.ZS,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,4.704880e+00,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1007,South Africa,ZAF,"Population, total",SP.POP.TOTL,3.611933e+07,3.739385e+07,3.866868e+07,3.987757e+07,4.091096e+07,4.176076e+07,...,5.387362e+07,5.472955e+07,5.587650e+07,5.642227e+07,5.664121e+07,5.733964e+07,5.808706e+07,5.880193e+07,5.939226e+07,5.989388e+07
1008,South Africa,ZAF,"Population, female",SP.POP.TOTL.FE.IN,1.860422e+07,1.923134e+07,1.985855e+07,2.045496e+07,2.097209e+07,2.147196e+07,...,2.783750e+07,2.822886e+07,2.872109e+07,2.900411e+07,2.917594e+07,2.951729e+07,2.987911e+07,3.022114e+07,3.049765e+07,3.072588e+07
1009,South Africa,ZAF,Rural population growth (annual %),SP.RUR.TOTL.ZG,2.425981e+00,2.386537e+00,2.259287e+00,1.975314e+00,1.474632e+00,1.030558e+00,...,-6.707473e-02,1.324969e-01,6.175991e-01,-4.972837e-01,-1.092206e+00,-2.642846e-01,-2.051978e-01,-2.907605e-01,-5.227356e-01,-6.883203e-01
1010,South Africa,ZAF,Urban population growth (annual %),SP.URB.GROW,4.562023e+00,4.518988e+00,4.392617e+00,4.106003e+00,3.547016e+00,2.972648e+00,...,2.181680e+00,2.386572e+00,2.873153e+00,1.760214e+00,1.163250e+00,1.989500e+00,2.047266e+00,1.965305e+00,1.728207e+00,1.557749e+00
1011,South Africa,ZAF,Urban population,SP.URB.TOTL,1.821823e+07,1.906040e+07,1.991631e+07,2.075109e+07,2.150034e+07,2.214907e+07,...,3.436760e+07,3.519767e+07,3.622362e+07,3.686688e+07,3.729824e+07,3.804772e+07,3.883468e+07,3.960545e+07,4.029586e+07,4.092849e+07

In [54]:
# renombrar columnas
df_api.rename(columns={'country_name': 'country', 'economy': 'country_code', 'indicator_name': 'indicator', 'series': 'indicator_code'}, inplace=True)

In [55]:
df_api

,country,country_code,indicator,indicator_code,YR1987,YR1988,YR1989,YR1990,YR1991,YR1992,...,YR2013,YR2014,YR2015,YR2016,YR2017,YR2018,YR2019,YR2020,YR2021,YR2022
0,Afghanistan,AFG,"Inflation, consumer prices (annual %)",FP.CPI.TOTL.ZG,NaN,NaN,NaN,NaN,NaN,NaN,...,7.385772e+00,4.673996e+00,-6.617092e-01,4.383892e+00,4.975952e+00,6.261491e-01,2.302373e+00,NaN,NaN,NaN
1,Afghanistan,AFG,"Inflation, GDP deflator (annual %)",NY.GDP.DEFL.KD.ZG,NaN,NaN,NaN,NaN,NaN,NaN,...,4.822785e+00,5.669445e-01,2.447563e+00,-2.197526e+00,2.403656e+00,2.071349e+00,6.521480e+00,7.821667e+00,4.774289e-01,NaN
2,Afghanistan,AFG,"Lower secondary completion rate, total (% of r...",SE.SEC.CMPT.LO.ZS,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,5.252132e+01,5.469328e+01,5.673693e+01,5.972179e+01,NaN,NaN,NaN
3,Afghanistan,AFG,"Educational attainment, at least completed low...",SE.SEC.CUAT.LO.ZS,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,1.312581e+01,NaN,NaN,NaN,NaN,NaN,1.163192e+01,1.534292e+01
4,Afghanistan,AFG,"Educational attainment, at least completed pos...",SE.SEC.CUAT.PO.ZS,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,4.704880e+00,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1007,South Africa,ZAF,"Population, total",SP.POP.TOTL,3.611933e+07,3.739385e+07,3.866868e+07,3.987757e+07,4.091096e+07,4.176076e+07,...,5.387362e+07,5.472955e+07,5.587650e+07,5.642227e+07,5.664121e+07,5.733964e+07,5.808706e+07,5.880193e+07,5.939226e+07,5.989388e+07
1008,South Africa,ZAF,"Population, female",SP.POP.TOTL.FE.IN,1.860422e+07,1.923134e+07,1.985855e+07,2.045496e+07,2.097209e+07,2.147196e+07,...,2.783750e+07,2.822886e+07,2.872109e+07,2.900411e+07,2.917594e+07,2.951729e+07,2.987911e+07,3.022114e+07,3.049765e+07,3.072588e+07
1009,South Africa,ZAF,Rural population growth (annual %),SP.RUR.TOTL.ZG,2.425981e+00,2.386537e+00,2.259287e+00,1.975314e+00,1.474632e+00,1.030558e+00,...,-6.707473e-02,1.324969e-01,6.175991e-01,-4.972837e-01,-1.092206e+00,-2.642846e-01,-2.051978e-01,-2.907605e-01,-5.227356e-01,-6.883203e-01
1010,South Africa,ZAF,Urban population growth (annual %),SP.URB.GROW,4.562023e+00,4.518988e+00,4.392617e+00,4.106003e+00,3.547016e+00,2.972648e+00,...,2.181680e+00,2.386572e+00,2.873153e+00,1.760214e+00,1.163250e+00,1.989500e+00,2.047266e+00,1.965305e+00,1.728207e+00,1.557749e+00
1011,South Africa,ZAF,Urban population,SP.URB.TOTL,1.821823e+07,1.906040e+07,1.991631e+07,2.075109e+07,2.150034e+07,2.214907e+07,...,3.436760e+07,3.519767e+07,3.622362e+07,3.686688e+07,3.729824e+07,3.804772e+07,3.883468e+07,3.960545e+07,4.029586e+07,4.092849e+07