In [1]:
# importar librerías
import pandas as pd
import wbdata as wb

In [2]:
# Definir listas de indicadores y países
indicators_list = [
                     "SP.DYN.LE00.IN", "SP.DYN.LE00.FE.IN", "SP.DYN.LE00.MA.IN", "SP.POP.GROW",
                     "SP.RUR.TOTL.ZG", "SP.URB.GROW", "SP.POP.TOTL", "SP.URB.TOTL", "SP.RUR.TOTL"
                     "SP.POP.TOTL.MA.IN", "SP.POP.TOTL.FE.IN", "SP.POP.0014.TO", "SP.POP.0014.MA.IN"
                     "SP.POP.0014.FE.IN", "SP.POP.1564.TO", "SP.POP.1564.MA.IN", "SP.POP.1564.FE.IN",
                     "SP.POP.65UP.TO", "SP.POP.65UP.MA.IN", "SP.POP.65UP.FE.IN", "NY.GDP.PCAP.KD.ZG"
                     "NY.GDP.PCAP.CD", "NY.GDP.DEFL.KD.ZG", "FP.CPI.TOTL.ZG", "SE.SEC.CUAT.LO.ZS",
                     "SE.SEC.CUAT.UP.ZS", "SE.SEC.CUAT.PO.ZS", "SE.SEC.CMPT.LO.ZS", "SH.XPD.GHED.PC.CD"
                     "SH.XPD.OOPC.PC.CD", "SH.XPD.PVTD.PC.CD"
                  ]
country_list = [
                    "AFG", "ARE", "ARG", "AUS", "AUT", "BFA", "BRA", "CAN", "CHE", "CHN",
                    "COL", "CRI", "CUB", "DEU", "DNK", "DZA", "ECU", "EGY", "ESP", "FIN", 
                    "FJI", "GBR", "GRC", "IND", "JPN", "KEN", "KHM", "MAR", "MEX", "NER", 
                    "NLD", "NOR", "NPL", "NZL", "RUS", "RWA", "SAU", "SGP", "SLE", "TCD", 
                    "USA", "VEN", "WSM", "ZAF"                
               ]

In [3]:
# Obtener nombres de indicadores
indicators_names = {}
all_indicators = wb.get_indicator(source=2)
for indicator in indicators_list:
    matching_indicators = [i for i in all_indicators if i['id'] == indicator]
    if matching_indicators:
        indicators_names[indicator] = matching_indicators[0]['name']

# Obtener nombres de países
countries_names = {}
for country in country_list:
    info = wb.get_country(country_id=country)
    countries_names[country] = info[0]['name']

In [4]:
# visualizar los diccionarios creados
print(indicators_names)
countries_names

{'SP.DYN.LE00.IN': 'Life expectancy at birth, total (years)', 'SP.DYN.LE00.FE.IN': 'Life expectancy at birth, female (years)', 'SP.DYN.LE00.MA.IN': 'Life expectancy at birth, male (years)', 'SP.POP.GROW': 'Population growth (annual %)', 'SP.RUR.TOTL.ZG': 'Rural population growth (annual %)', 'SP.URB.GROW': 'Urban population growth (annual %)', 'SP.POP.TOTL': 'Population, total', 'SP.URB.TOTL': 'Urban population', 'SP.POP.TOTL.FE.IN': 'Population, female', 'SP.POP.0014.TO': 'Population ages 0-14, total', 'SP.POP.1564.TO': 'Population ages 15-64, total', 'SP.POP.1564.MA.IN': 'Population ages 15-64, male', 'SP.POP.1564.FE.IN': 'Population ages 15-64, female', 'SP.POP.65UP.TO': 'Population ages 65 and above, total', 'SP.POP.65UP.MA.IN': 'Population ages 65 and above, male', 'SP.POP.65UP.FE.IN': 'Population ages 65 and above, female', 'NY.GDP.DEFL.KD.ZG': 'Inflation, GDP deflator (annual %)', 'FP.CPI.TOTL.ZG': 'Inflation, consumer prices (annual %)', 'SE.SEC.CUAT.LO.ZS': 'Educational attainment, at least completed lower secondary, population 25+, total (%) (cumulative)', 'SE.SEC.CUAT.UP.ZS': 'Educational attainment, at least completed upper secondary, population 25+, total (%) (cumulative)', 'SE.SEC.CUAT.PO.ZS': 'Educational attainment, at least completed post-secondary, population 25+, total (%) (cumulative)', 'SE.SEC.CMPT.LO.ZS': 'Lower secondary completion rate, total (% of relevant age group)', 'SH.XPD.PVTD.PC.CD': 'Domestic private health expenditure per capita (current US$)'}

{'AFG': 'Afghanistan',
 'ARE': 'United Arab Emirates',
 'ARG': 'Argentina',
 'AUS': 'Australia',
 'AUT': 'Austria',
 'BFA': 'Burkina Faso',
 'BRA': 'Brazil',
 'CAN': 'Canada',
 'CHE': 'Switzerland',
 'CHN': 'China',
 'COL': 'Colombia',
 'CRI': 'Costa Rica',
 'CUB': 'Cuba',
 'DEU': 'Germany',
 'DNK': 'Denmark',
 'DZA': 'Algeria',
 'ECU': 'Ecuador',
 'EGY': 'Egypt, Arab Rep.',
 'ESP': 'Spain',
 'FIN': 'Finland',
 'FJI': 'Fiji',
 'GBR': 'United Kingdom',
 'GRC': 'Greece',
 'IND': 'India',
 'JPN': 'Japan',
 'KEN': 'Kenya',
 'KHM': 'Cambodia',
 'MAR': 'Morocco',
 'MEX': 'Mexico',
 'NER': 'Niger',
 'NLD': 'Netherlands',
 'NOR': 'Norway',
 'NPL': 'Nepal',
 'NZL': 'New Zealand',
 'RUS': 'Russian Federation',
 'RWA': 'Rwanda',
 'SAU': 'Saudi Arabia',
 'SGP': 'Singapore',
 'SLE': 'Sierra Leone',
 'TCD': 'Chad',
 'USA': 'United States',
 'VEN': 'Venezuela, RB',
 'WSM': 'Samoa',
 'ZAF': 'South Africa'}

In [5]:
# crear dataframe con los diccionarios creados y con frecuencia anual
data = wb.get_dataframe(indicators=indicators_names, country=countries_names, freq='Y')

In [6]:
# visualizar el dataframe creado
data

                   Life expectancy at birth, total (years)  \
country      date
Afghanistan  2022                                      NaN
             2021                                   61.982
             2020                                   62.575
             2019                                   63.565
             2018                                   63.081
...                                                    ...
South Africa 1964                                   53.906
             1963                                   53.633
             1962                                   53.376
             1961                                   53.085
             1960                                   52.669

                   Life expectancy at birth, female (years)  \
country      date
Afghanistan  2022                                       NaN
             2021                                    65.279
             2020                                    65.432
             2019                                    66.677
             2018                                    66.458
...                                                     ...
South Africa 1964                                    56.217
             1963                                    55.905
             1962                                    55.595
             1961                                    55.254
             1960                                    54.751

                   Life expectancy at birth, male (years)  \
country      date
Afghanistan  2022                                     NaN
             2021                                  58.915
             2020                                  59.866
             2019                                  60.619
             2018                                  59.923
...                                                   ...
South Africa 1964                                  51.889
             1963                                  51.656
             1962                                  51.450
             1961                                  51.206
             1960                                  50.877

                   Population growth (annual %)  \
country      date
Afghanistan  2022                      2.534498
             2021                      2.851358
             2020                      3.134747
             2019                      2.908529
             2018                      2.885208
...                                         ...
South Africa 1964                      3.061378
             1963                      3.033440
             1962                      2.978651
             1961                      2.799492
             1960                           NaN

                   Rural population growth (annual %)  \
country      date
Afghanistan  2022                            2.123806
             2021                            2.461275
             2020                            2.767724
             2019                            2.560297
             2018                            2.556909
...                                               ...
South Africa 1964                            2.845963
             1963                            2.818505
             1962                            2.766043
             1961                            2.472996
             1960                                 NaN

                   Urban population growth (annual %)  Population, total  \
country      date
Afghanistan  2022                            3.675647         41128771.0
             2021                            3.951857         40099462.0
             2020                            4.185357         38972230.0
             2019                            3.919287         37769499.0
             2018                            3.850833         36686784.0
...                                               ...                ...
South Africa 1964                            3.303544         18603097.0
             1963                            3.276173         18042215.0
             1962                            3.219853         17503133.0
             1961                            3.172042         16989464.0
             1960                                 NaN         16520441.0

                   Urban population  Population, female  \
country      date
Afghanistan  2022        10946834.0          20362329.0
             2021        10551772.0          19844584.0
             2020        10142913.0          19279930.0
             2019         9727157.0          18679089.0
             2018         9353296.0          18136922.0
...                             ...                 ...
South Africa 1964         8768384.0           9107018.0
             1963         8483449.0           8813888.0
             1962         8210020.0           8532023.0
             1961         7949880.0           8263745.0
             1960         7701664.0           8017980.0

                   Population ages 0-14, total  ...  \
country      date                               ...
Afghanistan  2022                   17739100.0  ...
             2021                   17413008.0  ...
             2020                   17072920.0  ...
             2019                   16728622.0  ...
             2018                   16402090.0  ...
...                                        ...  ...
South Africa 1964                    7827378.0  ...
             1963                    7599960.0  ...
             1962                    7390614.0  ...
             1961                    7186834.0  ...
             1960                    7013285.0  ...

                   Population ages 65 and above, total  \
country      date
Afghanistan  2022                             984763.0
             2021                             964014.0
             2020                             941940.0
             2019                             913174.0
             2018                             883085.0
...                                                ...
South Africa 1964                             623810.0
             1963                             603925.0
             1962                             586491.0
             1961                             571469.0
             1960                             558526.0

                   Population ages 65 and above, male  \
country      date
Afghanistan  2022                            421409.0
             2021                            414713.0
             2020                            407078.0
             2019                            395783.0
             2018                            383903.0
...                                               ...
South Africa 1964                            283978.0
             1963                            274898.0
             1962                            267376.0
             1961                            261202.0
             1960                            256533.0

                   Population ages 65 and above, female  \
country      date
Afghanistan  2022                              563354.0
             2021                              549301.0
             2020                              534863.0
             2019                              517390.0
             2018                              499182.0
...                                                 ...
South Africa 1964                              339832.0
             1963                              329027.0
             1962                              319115.0
             1961                              310268.0
             1960                              301993.0

                   Inflation, GDP deflator (annual %)  \
country      date
Afghanistan  2022                                 NaN
             2021                            0.477429
             2020                            7.821667
             2019                            6.521480
             2018                            2.071349
...                                               ...
South Africa 1964                            2.048646
             1963                            3.003934
             1962                            0.183995
             1961                            1.552451
             1960                                 NaN

                   Inflation, consumer prices (annual %)  \
country      date
Afghanistan  2022                                    NaN
             2021                                    NaN
             2020                                    NaN
             2019                               2.302373
             2018                               0.626149
...                                                  ...
South Africa 1964                               2.534973
             1963                               1.337970
             1962                               1.246285
             1961                               2.102374
             1960                               1.288859

                   Educational attainment, at least completed lower secondary, population 25+, total (%) (cumulative)  \
country      date
Afghanistan  2022                                           15.34292
             2021                                           11.63192
             2020                                                NaN
             2019                                                NaN
             2018                                                NaN
...                                                              ...
South Africa 1964                                                NaN
             1963                                                NaN
             1962                                                NaN
             1961                                                NaN
             1960                                                NaN

                   Educational attainment, at least completed upper secondary, population 25+, total (%) (cumulative)  \
country      date
Afghanistan  2022                                           12.59733
             2021                                            9.46131
             2020                                                NaN
             2019                                                NaN
             2018                                                NaN
...                                                              ...
South Africa 1964                                                NaN
             1963                                                NaN
             1962                                                NaN
             1961                                                NaN
             1960                                                NaN

                   Educational attainment, at least completed post-secondary, population 25+, total (%) (cumulative)  \
country      date
Afghanistan  2022                                                NaN
             2021                                            4.70488
             2020                                                NaN
             2019                                                NaN
             2018                                                NaN
...                                                              ...
South Africa 1964                                                NaN
             1963                                                NaN
             1962                                                NaN
             1961                                                NaN
             1960                                                NaN

                   Lower secondary completion rate, total (% of relevant age group)  \
country      date
Afghanistan  2022                                                NaN
             2021                                                NaN
             2020                                                NaN
             2019                                          59.721790
             2018                                          56.736931
...                                                              ...
South Africa 1964                                                NaN
             1963                                                NaN
             1962                                                NaN
             1961                                                NaN
             1960                                                NaN

                   Domestic private health expenditure per capita (current US$)
country      date
Afghanistan  2022                                                NaN
             2021                                          62.900228
             2020                                          61.204815
             2019                                          57.025428
             2018                                          54.483534
...                                                              ...
South Africa 1964                                                NaN
             1963                                                NaN
             1962                                                NaN
             1961                                                NaN
             1960                                                NaN

[2772 rows x 23 columns]

In [7]:
# Restablecer el índice del DataFrame
df_api = data.reset_index()

In [8]:
# visualizar el dataframe resultante
df_api

,country,date,"Life expectancy at birth, total (years)","Life expectancy at birth, female (years)","Life expectancy at birth, male (years)",Population growth (annual %),Rural population growth (annual %),Urban population growth (annual %),"Population, total",Urban population,...,"Population ages 65 and above, total","Population ages 65 and above, male","Population ages 65 and above, female","Inflation, GDP deflator (annual %)","Inflation, consumer prices (annual %)","Educational attainment, at least completed lower secondary, population 25+, total (%) (cumulative)","Educational attainment, at least completed upper secondary, population 25+, total (%) (cumulative)","Educational attainment, at least completed post-secondary, population 25+, total (%) (cumulative)","Lower secondary completion rate, total (% of relevant age group)",Domestic private health expenditure per capita (current US$)
0,Afghanistan,2022,NaN,NaN,NaN,2.534498,2.123806,3.675647,41128771.0,10946834.0,...,984763.0,421409.0,563354.0,NaN,NaN,15.34292,12.59733,NaN,NaN,NaN
1,Afghanistan,2021,61.982,65.279,58.915,2.851358,2.461275,3.951857,40099462.0,10551772.0,...,964014.0,414713.0,549301.0,0.477429,NaN,11.63192,9.46131,4.70488,NaN,62.900228
2,Afghanistan,2020,62.575,65.432,59.866,3.134747,2.767724,4.185357,38972230.0,10142913.0,...,941940.0,407078.0,534863.0,7.821667,NaN,NaN,NaN,NaN,NaN,61.204815
3,Afghanistan,2019,63.565,66.677,60.619,2.908529,2.560297,3.919287,37769499.0,9727157.0,...,913174.0,395783.0,517390.0,6.521480,2.302373,NaN,NaN,NaN,59.721790,57.025428
4,Afghanistan,2018,63.081,66.458,59.923,2.885208,2.556909,3.850833,36686784.0,9353296.0,...,883085.0,383903.0,499182.0,2.071349,0.626149,NaN,NaN,NaN,56.736931,54.483534
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2767,South Africa,1964,53.906,56.217,51.889,3.061378,2.845963,3.303544,18603097.0,8768384.0,...,623810.0,283978.0,339832.0,2.048646,2.534973,NaN,NaN,NaN,NaN,NaN
2768,South Africa,1963,53.633,55.905,51.656,3.033440,2.818505,3.276173,18042215.0,8483449.0,...,603925.0,274898.0,329027.0,3.003934,1.337970,NaN,NaN,NaN,NaN,NaN
2769,South Africa,1962,53.376,55.595,51.450,2.978651,2.766043,3.219853,17503133.0,8210020.0,...,586491.0,267376.0,319115.0,0.183995,1.246285,NaN,NaN,NaN,NaN,NaN
2770,South Africa,1961,53.085,55.254,51.206,2.799492,2.472996,3.172042,16989464.0,7949880.0,...,571469.0,261202.0,310268.0,1.552451,2.102374,NaN,NaN,NaN,NaN,NaN
2771,South Africa,1960,52.669,54.751,50.877,NaN,NaN,NaN,16520441.0,7701664.0,...,558526.0,256533.0,301993.0,NaN,1.288859,NaN,NaN,NaN,NaN,NaN

In [9]:
# eliminar los años anteriores a los años escogidos
df_api_final = df_api[~df_api['date'].astype(str).str[:4].between('1960', '1986')]

In [10]:
# resetear el índice
df_api_final = df_api_final.reset_index(drop=True)

In [11]:
# verificar, los países se repiten 35 veces, el siguiente país debería comenzar en la fila 36
df_api_final.head(40)

,country,date,"Life expectancy at birth, total (years)","Life expectancy at birth, female (years)","Life expectancy at birth, male (years)",Population growth (annual %),Rural population growth (annual %),Urban population growth (annual %),"Population, total",Urban population,...,"Population ages 65 and above, total","Population ages 65 and above, male","Population ages 65 and above, female","Inflation, GDP deflator (annual %)","Inflation, consumer prices (annual %)","Educational attainment, at least completed lower secondary, population 25+, total (%) (cumulative)","Educational attainment, at least completed upper secondary, population 25+, total (%) (cumulative)","Educational attainment, at least completed post-secondary, population 25+, total (%) (cumulative)","Lower secondary completion rate, total (% of relevant age group)",Domestic private health expenditure per capita (current US$)
0,Afghanistan,2022,NaN,NaN,NaN,2.534498,2.123806,3.675647,41128771.0,10946834.0,...,984763.0,421409.0,563354.0,NaN,NaN,15.342920,12.597330,NaN,NaN,NaN
1,Afghanistan,2021,61.982,65.279,58.915,2.851358,2.461275,3.951857,40099462.0,10551772.0,...,964014.0,414713.0,549301.0,0.477429,NaN,11.631920,9.461310,4.704880,NaN,62.900228
2,Afghanistan,2020,62.575,65.432,59.866,3.134747,2.767724,4.185357,38972230.0,10142913.0,...,941940.0,407078.0,534863.0,7.821667,NaN,NaN,NaN,NaN,NaN,61.204815
3,Afghanistan,2019,63.565,66.677,60.619,2.908529,2.560297,3.919287,37769499.0,9727157.0,...,913174.0,395783.0,517390.0,6.521480,2.302373,NaN,NaN,NaN,59.721790,57.025428
4,Afghanistan,2018,63.081,66.458,59.923,2.885208,2.556909,3.850833,36686784.0,9353296.0,...,883085.0,383903.0,499182.0,2.071349,0.626149,NaN,NaN,NaN,56.736931,54.483534
5,Afghanistan,2017,63.016,66.099,60.105,2.866492,2.559272,3.781557,35643418.0,8999963.0,...,855377.0,373212.0,482165.0,2.403656,4.975952,NaN,NaN,NaN,54.693279,50.505792
6,Afghanistan,2016,63.136,65.096,61.193,2.581549,2.292555,3.452643,34636207.0,8665979.0,...,830919.0,363928.0,466990.0,-2.197526,4.383892,NaN,NaN,NaN,52.521320,46.713933
7,Afghanistan,2015,62.659,64.576,60.760,3.121341,2.834511,3.996008,33753499.0,8371880.0,...,812047.0,357248.0,454799.0,2.447563,-0.661709,13.125810,9.792360,NaN,NaN,47.075262
8,Afghanistan,2014,62.545,64.274,60.812,3.657576,3.374206,4.531769,32716210.0,8043935.0,...,788186.0,348024.0,440162.0,0.566945,4.673996,NaN,NaN,NaN,NaN,43.972053
9,Afghanistan,2013,62.417,64.027,60.791,3.466788,3.185537,4.344553,31541209.0,7687539.0,...,758025.0,336319.0,421706.0,4.822785,7.385772,NaN,NaN,NaN,NaN,40.566940
10,Afghanistan,2012,61.923,63.514,60.317,4.077628,3.798483,4.958981,30466479.0,7360701.0,...,728754.0,325455.0,403298.0,7.301756,6.441213,NaN,NaN,NaN,NaN,39.189833
11,Afghanistan,2011,61.419,62.993,59.825,3.689508,3.412449,4.574493,29249157.0,7004588.0,...,694340.0,311127.0,383213.0,16.593347,11.804186,NaN,NaN,NaN,NaN,38.358640
12,Afghanistan,2010,60.851,62.408,59.278,2.894904,2.621229,3.779279,28189672.0,6691382.0,...,663424.0,298195.0,365229.0,3.814630,2.178538,NaN,NaN,NaN,NaN,36.796546
13,Afghanistan,2009,60.364,61.892,58.820,3.561288,3.289664,4.449269,27385307.0,6443215.0,...,639527.0,288735.0,350793.0,-2.163404,-6.811161,NaN,NaN,NaN,NaN,31.484861
14,Afghanistan,2008,59.852,61.529,58.172,2.002333,1.732743,2.893949,26427199.0,6162823.0,...,612481.0,277012.0,335468.0,2.096289,26.418664,NaN,NaN,NaN,NaN,30.138657
15,Afghanistan,2007,59.111,60.909,57.342,1.793196,1.525627,2.688468,25903301.0,5987030.0,...,597256.0,271683.0,325573.0,22.527756,8.680571,NaN,NaN,NaN,NaN,25.575033
16,Afghanistan,2006,58.684,60.243,57.133,4.139678,3.875415,5.034216,25442944.0,5828215.0,...,585793.0,268256.0,317538.0,7.199751,6.784597,NaN,NaN,NaN,NaN,22.217647
17,Afghanistan,2005,58.361,59.697,57.013,3.576508,3.314227,4.474690,24411191.0,5542073.0,...,561314.0,257162.0,304151.0,10.912774,12.686269,NaN,NaN,NaN,17.385929,19.827078
18,Afghanistan,2004,57.944,59.216,56.658,3.933178,3.743680,4.588653,23553551.0,5299549.0,...,540942.0,247897.0,293046.0,11.271432,NaN,NaN,NaN,NaN,NaN,18.113810
19,Afghanistan,2003,57.344,58.650,56.032,7.541019,7.422604,7.953448,22645130.0,5061866.0,...,519460.0,238463.0,280996.0,11.655238,NaN,NaN,NaN,NaN,NaN,15.333161
20,Afghanistan,2002,56.454,57.672,55.227,6.449321,6.331048,6.863453,21000256.0,4674867.0,...,480661.0,221096.0,259565.0,NaN,NaN,NaN,NaN,NaN,NaN,14.520330
21,Afghanistan,2001,55.798,57.344,54.272,0.742517,0.625667,1.153839,19688632.0,4364773.0,...,449855.0,207422.0,242433.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
22,Afghanistan,2000,55.298,56.858,53.762,1.443803,1.325806,1.861377,19542982.0,4314700.0,...,446519.0,206385.0,240135.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
23,Afghanistan,1999,54.846,56.300,53.410,4.077879,3.961297,4.492655,19262847.0,4235130.0,...,440223.0,203924.0,236299.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
24,Afghanistan,1998,52.943,54.818,51.134,3.882931,3.767769,4.294824,18493132.0,4049071.0,...,422731.0,196318.0,226413.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
25,Afghanistan,1997,53.634,55.151,52.153,3.910605,3.794297,4.328815,17788819.0,3878852.0,...,406736.0,189388.0,217349.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
26,Afghanistan,1996,53.243,54.806,51.722,4.103022,3.988129,4.518348,17106595.0,3714526.0,...,390765.0,182357.0,208408.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
27,Afghanistan,1995,52.544,54.087,51.039,6.046536,5.931765,6.463628,16418912.0,3550426.0,...,374319.0,175015.0,199303.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
28,Afghanistan,1994,51.495,53.544,49.531,9.864262,9.749628,10.283085,15455555.0,3328199.0,...,351470.0,164634.0,186836.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
29,Afghanistan,1993,51.466,52.739,50.216,14.964455,14.851229,15.380336,14003760.0,3002966.0,...,317195.0,148782.0,168413.0,NaN,NaN,NaN,NaN,NaN,21.686110,NaN
30,Afghanistan,1992,47.596,50.320,45.070,11.522524,11.409417,11.940176,12057433.0,2574865.0,...,271765.0,127606.0,144159.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
31,Afghanistan,1991,46.663,49.144,44.353,0.469880,0.356909,0.889255,10745167.0,2285067.0,...,241354.0,113494.0,127860.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
32,Afghanistan,1990,45.967,48.397,43.709,0.202434,0.089590,0.623574,10694796.0,2264837.0,...,240267.0,113182.0,127085.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
33,Afghanistan,1989,45.158,47.610,42.891,2.751877,2.637888,3.179585,10673168.0,2250758.0,...,240097.0,113325.0,126772.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
34,Afghanistan,1988,43.958,46.569,41.572,0.586318,-0.275758,3.898014,10383460.0,2180319.0,...,233853.0,110633.0,123220.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
35,Afghanistan,1987,39.844,43.453,36.739,-1.210190,-2.043746,2.128391,10322758.0,2096965.0,...,233845.0,111022.0,122823.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
36,United Arab Emirates,2022,NaN,NaN,NaN,0.808075,-1.131758,1.087189,9441129.0,8265048.0,...,172674.0,92861.0,79813.0,13.853415,4.827889,NaN,NaN,NaN,NaN,NaN
37,United Arab Emirates,2021,78.710,80.937,77.216,0.834813,-1.122169,1.122749,9365145.0,8175678.0,...,164678.0,87638.0,77040.0,14.280830,-0.013860,84.432213,73.479637,55.191872,NaN,NaN
38,United Arab Emirates,2020,78.946,81.112,77.464,0.817694,-1.162238,1.115671,9287289.0,8084399.0,...,153610.0,79797.0,73813.0,-12.031305,-2.079403,NaN,NaN,NaN,111.690720,855.112094
39,United Arab Emirates,2019,79.726,81.907,78.175,0.779087,-1.221806,1.087204,9211657.0,7994705.0,...,135505.0,68526.0,66979.0,-3.194409,-1.931081,84.167717,71.523758,54.092709,129.953690,932.007732